# Generated by Django 3.0 on 2020-03-09 17:46

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('_99popularity', models.FloatField()),
                ('director', models.CharField(max_length=100)),
                ('imdb_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('genre', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
            ],
        ),
    ]
